# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\x0foverbabel.audio\"\x0f\n\rStreamRequest\"1\n\rSubtitleBatch\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\ntranslated\x18\x02 \x01(\t\"\r\n\x0bPingRequest\"\x17\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xa5\x01\n\x0c\x41udioService\x12S\n\x0fStreamSubtitles\x12\x1e.overbabel.audio.StreamRequest\x1a\x1e.overbabel.audio.SubtitleBatch0\x01\x12@\n\x04Ping\x12\x1c.overbabel.audio.PingRequest\x1a\x1a.overbabel.audio.PingReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=32
  _globals['_STREAMREQUEST']._serialized_end=47
  _globals['_SUBTITLEBATCH']._serialized_start=49
  _globals['_SUBTITLEBATCH']._serialized_end=98
  _globals['_PINGREQUEST']._serialized_start=100
  _globals['_PINGREQUEST']._serialized_end=113
  _globals['_PINGREPLY']._serialized_start=115
  _globals['_PINGREPLY']._serialized_end=138
  _globals['_AUDIOSERVICE']._serialized_start=141
  _globals['_AUDIOSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
