# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from overbabel_core.ipc import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTranslations = channel.unary_stream(
                '/overbabel.vision.VisionService/StreamTranslations',
                request_serializer=vision__pb2.StreamRequest.SerializeToString,
                response_deserializer=vision__pb2.TranslationBatch.FromString,
                _registered_method=True)
        self.ReloadEngine = channel.unary_unary(
                '/overbabel.vision.VisionService/ReloadEngine',
                request_serializer=vision__pb2.ReloadEngineRequest.SerializeToString,
                response_deserializer=vision__pb2.ReloadEngineReply.FromString,
                _registered_method=True)


class VisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTranslations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTranslations': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTranslations,
                    request_deserializer=vision__pb2.StreamRequest.FromString,
                    response_serializer=vision__pb2.TranslationBatch.SerializeToString,
            ),
            'ReloadEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadEngine,
                    request_deserializer=vision__pb2.ReloadEngineRequest.FromString,
                    response_serializer=vision__pb2.ReloadEngineReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'overbabel.vision.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('overbabel.vision.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTranslations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/overbabel.vision.VisionService/StreamTranslations',
            vision__pb2.StreamRequest.SerializeToString,
            vision__pb2.TranslationBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/overbabel.vision.VisionService/ReloadEngine',
            vision__pb2.ReloadEngineRequest.SerializeToString,
            vision__pb2.ReloadEngineReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
