# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "vision.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cvision.proto\x12\x10overbabel.vision"#\n\rStreamRequest\x12\x12\n\nenable_ocr\x18\x01 \x01(\x08"V\n\x10TranslationBatch\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.overbabel.vision.TranslationItem\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04"h\n\x0fTranslationItem\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\x12\x0b\n\x03tag\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\x06 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65nt\x18\x07 \x01(\x08"C\n\x13ReloadEngineRequest\x12\x12\n\nocr_engine\x18\x01 \x01(\t\x12\x18\n\x10translate_engine\x18\x02 \x01(\t"0\n\x11ReloadEngineReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc8\x01\n\rVisionService\x12[\n\x12StreamTranslations\x12\x1f.overbabel.vision.StreamRequest\x1a".overbabel.vision.TranslationBatch0\x01\x12Z\n\x0cReloadEngine\x12%.overbabel.vision.ReloadEngineRequest\x1a#.overbabel.vision.ReloadEngineReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "vision_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STREAMREQUEST"]._serialized_start = 34
    _globals["_STREAMREQUEST"]._serialized_end = 69
    _globals["_TRANSLATIONBATCH"]._serialized_start = 71
    _globals["_TRANSLATIONBATCH"]._serialized_end = 157
    _globals["_TRANSLATIONITEM"]._serialized_start = 159
    _globals["_TRANSLATIONITEM"]._serialized_end = 263
    _globals["_RELOADENGINEREQUEST"]._serialized_start = 265
    _globals["_RELOADENGINEREQUEST"]._serialized_end = 332
    _globals["_RELOADENGINEREPLY"]._serialized_start = 334
    _globals["_RELOADENGINEREPLY"]._serialized_end = 382
    _globals["_VISIONSERVICE"]._serialized_start = 385
    _globals["_VISIONSERVICE"]._serialized_end = 585
# @@protoc_insertion_point(module_scope)
